#!/bin/bash
# Update .env file with deployed Azure resource values
# This script retrieves actual values from deployed resources and updates .env

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
ENV_FILE="${ROOT_DIR}/.env"

# Configuration
AZURE_ENV_NAME="${AZURE_ENV_NAME:-dev}"
AZURE_LOCATION="${AZURE_LOCATION:-westus3}"
AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-finagentix-${AZURE_ENV_NAME}-rg}"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to update or add a variable in .env
update_env_var() {
    local key=$1
    local value=$2
    local env_file="${3:-$ENV_FILE}"
    
    if [ -z "$value" ] || [ "$value" = "null" ]; then
        echo -e "${YELLOW}⚠️  Skipping $key (no value)${NC}"
        return
    fi
    
    # Escape special characters in value for sed
    local escaped_value=$(printf '%s\n' "$value" | sed -e 's/[\/&]/\\&/g')
    
    if grep -q "^${key}=" "$env_file" 2>/dev/null; then
        # Update existing variable
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^${key}=.*|${key}=${escaped_value}|" "$env_file"
        else
            sed -i "s|^${key}=.*|${key}=${escaped_value}|" "$env_file"
        fi
        echo -e "${GREEN}✅ Updated $key${NC}"
    else
        # Add new variable at the end of appropriate section or file
        echo "${key}=${value}" >> "$env_file"
        echo -e "${GREEN}➕ Added $key${NC}"
    fi
}

# Create .env from template if it doesn't exist
ensure_env_file() {
    if [ ! -f "$ENV_FILE" ]; then
        if [ -f "${ROOT_DIR}/.env.template" ]; then
            echo "📄 Creating .env from template..."
            cp "${ROOT_DIR}/.env.template" "$ENV_FILE"
        else
            echo "📄 Creating new .env file..."
            cat > "$ENV_FILE" <<EOF
# FinagentiX Environment Configuration
# Auto-generated by deployment script

# Azure Infrastructure
AZURE_ENV_NAME=
AZURE_LOCATION=
AZURE_RESOURCE_GROUP=

# Azure OpenAI
AZURE_OPENAI_ENDPOINT=
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_API_VERSION=2024-08-01-preview
AZURE_OPENAI_GPT4_DEPLOYMENT=gpt-4o
AZURE_OPENAI_CHAT_DEPLOYMENT=gpt-4o
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=text-embedding-3-large

# Azure Managed Redis
REDIS_HOST=
REDIS_PORT=10000
REDIS_PASSWORD=
REDIS_SSL=true

# Azure Storage
AZURE_STORAGE_ACCOUNT_NAME=
AZURE_STORAGE_CONNECTION_STRING=

# Application Settings
LOG_LEVEL=INFO
ENVIRONMENT=development
EOF
        fi
    fi
}

# Get resource token from existing deployments
get_resource_token() {
    local token=$(az deployment group list -g "$AZURE_RESOURCE_GROUP" \
        --query "[?contains(name, 'stage0')].properties.parameters.resourceToken.value | [0]" -o tsv 2>/dev/null)
    echo "$token"
}

# Update infrastructure variables
update_infrastructure() {
    echo ""
    echo "🏗️  Updating Infrastructure Variables..."
    update_env_var "AZURE_ENV_NAME" "$AZURE_ENV_NAME"
    update_env_var "AZURE_LOCATION" "$AZURE_LOCATION"
    update_env_var "AZURE_RESOURCE_GROUP" "$AZURE_RESOURCE_GROUP"
}

# Update Redis variables from Azure Managed Redis
update_redis() {
    echo ""
    echo "🔴 Updating Redis Variables..."
    
    local resource_token=$(get_resource_token)
    local redis_cluster=$(az redisenterprise list -g "$AZURE_RESOURCE_GROUP" --query "[0].name" -o tsv 2>/dev/null)
    
    if [ -z "$redis_cluster" ] || [ "$redis_cluster" = "null" ]; then
        echo -e "${YELLOW}⚠️  No Redis cluster found in resource group${NC}"
        return 1
    fi
    
    echo "   Found Redis cluster: $redis_cluster"
    
    # Get Redis host
    local redis_host=$(az redisenterprise show -g "$AZURE_RESOURCE_GROUP" -n "$redis_cluster" \
        --query "hostName" -o tsv 2>/dev/null)
    
    # Get Redis password
    local redis_password=$(az redisenterprise database list-keys \
        -g "$AZURE_RESOURCE_GROUP" \
        --cluster-name "$redis_cluster" \
        --query "primaryKey" -o tsv 2>/dev/null)
    
    # Get Redis port (default 10000 for Azure Managed Redis)
    local redis_port="10000"
    
    update_env_var "REDIS_HOST" "$redis_host"
    update_env_var "REDIS_PORT" "$redis_port"
    update_env_var "REDIS_PASSWORD" "$redis_password"
    update_env_var "REDIS_SSL" "true"
    
    # Remove empty password setting if present
    if grep -q "^REDIS_ALLOW_EMPTY_PASSWORD=" "$ENV_FILE" 2>/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' '/^REDIS_ALLOW_EMPTY_PASSWORD=/d' "$ENV_FILE"
        else
            sed -i '/^REDIS_ALLOW_EMPTY_PASSWORD=/d' "$ENV_FILE"
        fi
        echo -e "${GREEN}🗑️  Removed REDIS_ALLOW_EMPTY_PASSWORD${NC}"
    fi
}

# Update Azure OpenAI variables
update_openai() {
    echo ""
    echo "🤖 Updating Azure OpenAI Variables..."
    
    local openai_resource=$(az cognitiveservices account list -g "$AZURE_RESOURCE_GROUP" \
        --query "[?kind=='OpenAI'] | [0].name" -o tsv 2>/dev/null)
    
    if [ -z "$openai_resource" ] || [ "$openai_resource" = "null" ]; then
        echo -e "${YELLOW}⚠️  No Azure OpenAI resource found in resource group${NC}"
        return 1
    fi
    
    echo "   Found OpenAI resource: $openai_resource"
    
    # Get endpoint
    local openai_endpoint=$(az cognitiveservices account show -g "$AZURE_RESOURCE_GROUP" -n "$openai_resource" \
        --query "properties.endpoint" -o tsv 2>/dev/null)
    
    # Get API key
    local openai_key=$(az cognitiveservices account keys list -g "$AZURE_RESOURCE_GROUP" -n "$openai_resource" \
        --query "key1" -o tsv 2>/dev/null)
    
    # Get deployments
    local gpt4_deployment=$(az cognitiveservices account deployment list -g "$AZURE_RESOURCE_GROUP" -n "$openai_resource" \
        --query "[?contains(properties.model.name, 'gpt-4')].name | [0]" -o tsv 2>/dev/null)
    local embedding_deployment=$(az cognitiveservices account deployment list -g "$AZURE_RESOURCE_GROUP" -n "$openai_resource" \
        --query "[?contains(properties.model.name, 'embedding')].name | [0]" -o tsv 2>/dev/null)
    
    update_env_var "AZURE_OPENAI_ENDPOINT" "$openai_endpoint"
    update_env_var "AZURE_OPENAI_API_KEY" "$openai_key"
    update_env_var "AZURE_OPENAI_GPT4_DEPLOYMENT" "${gpt4_deployment:-gpt-4o}"
    update_env_var "AZURE_OPENAI_CHAT_DEPLOYMENT" "${gpt4_deployment:-gpt-4o}"
    update_env_var "AZURE_OPENAI_EMBEDDING_DEPLOYMENT" "${embedding_deployment:-text-embedding-3-large}"
}

# Update Storage Account variables
update_storage() {
    echo ""
    echo "💾 Updating Storage Variables..."
    
    local storage_account=$(az storage account list -g "$AZURE_RESOURCE_GROUP" \
        --query "[0].name" -o tsv 2>/dev/null)
    
    if [ -z "$storage_account" ] || [ "$storage_account" = "null" ]; then
        echo -e "${YELLOW}⚠️  No Storage Account found in resource group${NC}"
        return 1
    fi
    
    echo "   Found Storage Account: $storage_account"
    
    # Get connection string
    local connection_string=$(az storage account show-connection-string \
        -g "$AZURE_RESOURCE_GROUP" -n "$storage_account" --query "connectionString" -o tsv 2>/dev/null)
    
    # Get account key
    local account_key=$(az storage account keys list -g "$AZURE_RESOURCE_GROUP" -n "$storage_account" \
        --query "[0].value" -o tsv 2>/dev/null)
    
    update_env_var "AZURE_STORAGE_ACCOUNT_NAME" "$storage_account"
    update_env_var "AZURE_STORAGE_CONNECTION_STRING" "$connection_string"
    update_env_var "AZURE_STORAGE_ACCOUNT_KEY" "$account_key"
}

# Update Debug VM IP
update_vm() {
    echo ""
    echo "🖥️  Updating VM Variables..."
    
    local vm_public_ip=$(az vm list -g "$AZURE_RESOURCE_GROUP" -d \
        --query "[?contains(name, 'debug')].publicIps | [0]" -o tsv 2>/dev/null)
    
    if [ -n "$vm_public_ip" ] && [ "$vm_public_ip" != "null" ]; then
        update_env_var "DEBUG_VM_IP" "$vm_public_ip"
    else
        echo -e "${YELLOW}⚠️  No Debug VM found in resource group${NC}"
    fi
}

# Update all variables
update_all() {
    echo "=========================================="
    echo "🔄 Updating .env with Azure Resources"
    echo "=========================================="
    echo "Resource Group: $AZURE_RESOURCE_GROUP"
    echo "Location: $AZURE_LOCATION"
    echo "Env File: $ENV_FILE"
    
    ensure_env_file
    
    update_infrastructure
    update_redis
    update_openai
    update_storage
    update_vm
    
    echo ""
    echo "=========================================="
    echo "✅ .env update complete!"
    echo "=========================================="
}

# Parse arguments
case "${1:-all}" in
    --infrastructure|-i)
        ensure_env_file
        update_infrastructure
        ;;
    --redis|-r)
        ensure_env_file
        update_redis
        ;;
    --openai|-o)
        ensure_env_file
        update_openai
        ;;
    --storage|-s)
        ensure_env_file
        update_storage
        ;;
    --vm|-v)
        ensure_env_file
        update_vm
        ;;
    --all|-a|all)
        update_all
        ;;
    --help|-h)
        echo "Usage: $0 [OPTION]"
        echo ""
        echo "Update .env file with deployed Azure resource values"
        echo ""
        echo "Options:"
        echo "  --all, -a          Update all variables (default)"
        echo "  --infrastructure, -i  Update infrastructure variables only"
        echo "  --redis, -r        Update Redis variables only"
        echo "  --openai, -o       Update Azure OpenAI variables only"
        echo "  --storage, -s      Update Storage variables only"
        echo "  --vm, -v           Update VM variables only"
        echo "  --help, -h         Show this help message"
        ;;
    *)
        echo "Unknown option: $1"
        echo "Use --help for usage information"
        exit 1
        ;;
esac
